# Generated by Django 2.2.2 on 2019-11-16 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 16, 12, 57, 42, 995395)),
        ),
    ]
