# Generated by Django 2.2.2 on 2019-11-22 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20191117_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.CharField(default=datetime.datetime(2019, 11, 22, 10, 41, 57, 263703), max_length=25, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 22, 10, 41, 27, 94018)),
        ),
    ]
