# Generated by Django 2.2.2 on 2019-11-22 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20191122_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 22, 10, 43, 36, 166704)),
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.CharField(max_length=25),
        ),
    ]
