# Generated by Django 2.2.2 on 2019-11-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20191122_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
