# Generated by Django 2.2.2 on 2019-11-23 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20191122_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='officeadmin',
        ),
    ]
