# Generated by Django 2.2.2 on 2019-11-23 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('subtitle', models.CharField(max_length=120)),
                ('content_text', models.TextField()),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_published', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='post.Post')),
            ],
        ),
    ]
