# Generated by Django 2.2.2 on 2019-11-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20191130_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
