# Generated by Django 2.2.2 on 2019-12-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_topic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(upload_to='topic_images/'),
        ),
    ]
