# Generated by Django 2.2.2 on 2019-12-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_postsection_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsection',
            name='tags',
        ),
    ]
