# Generated by Django 2.2.2 on 2019-12-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_remove_postsection_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsection',
            name='tag',
            field=models.CharField(default='<p>', max_length=255),
        ),
    ]
