# Generated by Django 2.2.2 on 2019-11-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ManyToManyField(null=True, related_name='tags', to='post.Images')),
                ('post', models.ManyToManyField(blank=True, null=True, related_name='tags', to='post.Post')),
            ],
        ),
    ]
